### ISSUE TITLE
Every example failing with `std.json.JSONException`

### ISSUE THREAD

**Issue by btbytes** [rejectedsoftware/vibe.d#1905]
This is while using vibe.d version 0.8.0: 

```
"dependencies": {
                "vibe-d": "~>0.8.0"
        },
```

Error message: 

```
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./rest-example
std.json.JSONException@std/json.d(1395): Got JSON of type int_, expected string.
Program exited with code 1
```

**Comment by s-ludwig** [comment]
I hit this issue with the examples/rest example for the latest 0.8.1-rc.4, but not for 0.8.0. The other examples appear to work fine. Can you confirm this? I've pushed a fix to master: f32fd06944ffc70ffce5c39002fc7bc92d0d639a

**Comment by s-ludwig** [comment]
Actually, nevermind, this was a different JSON error in the same example. I couldn't reproduce an issue on 0.8.0, though. Was it the original examples/rest/ example that failed?

**Comment by btbytes** [comment]
It is still failing on `master` even after the last patch. I'd changed the version to `0.8.0` (instead of ` {"path": "../../"}`) to see if bug was only introduced in the latest version.. 

```
Performing "debug" build using dmd for x86_64.
diet-ng 1.4.2: target for configuration "library" is up to date.
vibe-d:utils 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:data 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:core 0.8.1-rc.4+commit.1.gf32fd069: building configuration "libevent"...
vibe-d:crypto 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:stream 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:textfilter 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:inet 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:tls 0.8.1-rc.4+commit.1.gf32fd069: building configuration "openssl"...
vibe-d:http 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
vibe-d:web 0.8.1-rc.4+commit.1.gf32fd069: building configuration "library"...
rest-example ~master: building configuration "application"...
Non-@safe methods are deprecated in REST interfaces - Mark Example1.getSomeInfo as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example1.postSum as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example1.getter as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example2.queryAccumulateAll as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example3APINested.getNumber as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example3.getMyID as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example4.myNameDoesNotMatter as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example4.getParametersInURL as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example4.querySpecialParameterNames as @safe.
Non-@safe @before evaluators are deprecated - annotate evaluator function for parameter user of Example5.getSecret as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example5.getSecret as @safe.
Non-@safe @after evaluators are deprecated - annotate @after evaluator function for Example5.getSecret as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example6.getPortal as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example6.postAnswer as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example6.postConcat as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example6.postConcatBody as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark Example7.get as @safe.
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./rest-example
std.json.JSONException@std/json.d(1395): Got JSON of type int_, expected string.
Program exited with code 1
```

**Comment by s-ludwig** [comment]
Can you post the output of `dub -- --vvv` (maybe at https://pastebin.com/ due to the length)? Maybe that contains enough information to track down the cause, without being able to reproduce this locally.

**Comment by btbytes** [comment]
```
➜  rest git:(master) ✗  dub -- --vvv 
Performing "debug" build using dmd for x86_64.
diet-ng 1.4.2: target for configuration "library" is up to date.
vibe-d:utils 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:data 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:core 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "libevent" is up to date.
vibe-d:crypto 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:stream 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:textfilter 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:inet 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:tls 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "openssl" is up to date.
vibe-d:http 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
vibe-d:web 0.8.1-rc.4+commit.1.gf32fd069: target for configuration "library" is up to date.
rest-example ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./rest-example --vvv
[0C861001:00000000 dia] libevent version: 10C5D0B1F
[0C861001:00000000 dia] libevent is using 10C5D1DEF for events.
std.json.JSONException@std/json.d(1395): Got JSON of type int_, expected string.
Program exited with code 1
```

**Comment by thaven** [comment]
Isn't it just invalid JSON in the config file?

**Comment by btbytes** [comment]
I doubt that.. This is from a fresh checkout of vibe.d source code 

```
➜  rest git:(master) ✗ cat dub.json 
{
        "name": "rest-example",
        "description": "Shows how the REST interface generator can be used for RPC communication.",
        "dependencies": {
                "vibe-d:web": {"path": "../../"}
        },
        "versions": ["VibeDefaultMain"]
}%                          
```

**Comment by thaven** [comment]
I meant vibe.conf ;) Wouldn't be dub.json indeed. The error is clearly runtime.

**Comment by s-ludwig** [comment]
/etc/vibe/vibe.conf sounds like a good candidate indeed, since there seems to be no activity specific to the example yet and nothing else uses JSON at that stage.

**Comment by btbytes** [comment]
```
➜  vibe pwd           
/etc/vibe
➜  vibe cat vibe.conf 
{
        "uid": 70,
        "gid": 70
}
```

**Comment by s-ludwig** [comment]
Okay, that explains it then. Unfortunately the options code can currently only take the exact type that it was declared with. In case of "uid" and "gid" it's `string`, because names are also supported. So it needs to be `"70"` in this case.

But this is definitely something that should be improved. Either by accepting `int`, too, or by somehow at least transitioning to a different name (e.g. "user"/"group").

**Comment by btbytes** [comment]
This fixed the issue as per your suggestion: 

```
$ cat /etc/vibe/vibe.conf 
{
        "uid": "70",
        "gid": "70"
}

```
